CREATE TABLE `paciente` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `bairro` text,
  `cbo` text,
  `cep` text,
  `classificacaoFinal` text,
  `cnes` text,
  `cns` text,
  `codigoCbo` text,
  `codigoClassificacaoFinal` text,
  `codigoComunidadeTradicional` text,
  `codigoCondicoes` text,
  `codigoEstadoTeste` text,
  `codigoEstrangeiro` text,
  `codigoEvolucaoCaso` text,
  `codigoPaisOrigem` text,
  `codigoProfissionalSaude` text,
  `codigoProfissionalSeguranca` text,
  `codigoResultadoTeste` text,
  `codigoResultadoTesteSorologicoIgA` text,
  `codigoResultadoTesteSorologicoIgG` text,
  `codigoResultadoTesteSorologicoIgM` text,
  `codigoResultadoTesteSorologicoTotais` text,
  `codigoSexo` text,
  `codigoSintomas` text,
  `codigoTemCpf` text,
  `codigoTesteSorologico` text,
  `codigoTipoTeste` text,
  `codigoTipoTesteSorologico` text,
  `complemento` text,
  `comunidadeTradicional` text,
  `condicoes` text,
  `contemComunidadeTradicional` text,
  `cpf` text,
  `createdAt` datetime(6) DEFAULT NULL,
  `dataEncerramento` datetime(6) DEFAULT NULL,
  `dataInicioSintomas` datetime(6) DEFAULT NULL,
  `dataNascimento` datetime(6) DEFAULT NULL,
  `dataNotificacao` datetime(6) DEFAULT NULL,
  `dataTeste` datetime(6) DEFAULT NULL,
  `dataTesteSorologico` datetime(6) DEFAULT NULL,
  `descricaoRacaCor` text,
  `desnormalizarNome` text,
  `email` text,
  `estado` text,
  `estadoIBGE` text,
  `estadoNotificacao` text,
  `estadoNotificacaoIBGE` text,
  `estadoTeste` text,
  `estrangeiro` text,
  `etnia` text,
  `evolucaoCaso` text,
  `idOrigem` text,
  `idade` text,
  `labCnes` text,
  `logradouro` text,
  `municipio` text,
  `municipioIBGE` text,
  `municipioNotificacao` text,
  `municipioNotificacaoIBGE` text,
  `nomeCompleto` text,
  `nomeCompletoDesnormalizado` text,
  `nomeMae` text,
  `notificadorCNPJ` text,
  `notificadorCpf` text,
  `notificadorEmail` text,
  `notificadorNome` text,
  `numero` text,
  `numeroNotificacao` text,
  `origem` text,
  `outrosSintomas` text,
  `pUsuario` text,
  `pUsuarioAlteracao` text,
  `paisOrigem` text,
  `passaporte` text,
  `profissionalSaude` text,
  `profissionalSeguranca` text,
  `racaCor` text,
  `resultadoTeste` text,
  `resultadoTesteSorologicoIgA` text,
  `resultadoTesteSorologicoIgG` text,
  `resultadoTesteSorologicoIgM` text,
  `resultadoTesteSorologicoTotais` text,
  `rpa` text,
  `sexo` text,
  `sintomas` text,
  `sourceId` text,
  `telefone` text,
  `telefoneContato` text,
  `testeSorologico` text,
  `timestampNotificacao` text,
  `tipoTeste` text,
  `tipoTesteSorologico` text,
  `updatedAt` datetime(6) DEFAULT NULL,
  `versaoFormulario` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9711 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci